CREATE DATABASE NETFLIX_DB;
USE NETFLIX_DB;

-- CREATING THE TABLE STRUCTURE BASED ON DATASET
CREATE TABLE NETFLIX_DATASET(
SHOW_ID INT,
TITLE VARCHAR(150),
DIRECTOR VARCHAR(200),
CAST TEXT,
COUNTRY VARCHAR(150),
DATE_ADDED VARCHAR(30),
RELEASED_YEAR VARCHAR(10),
RATING VARCHAR(10),
DURATION VARCHAR(20),
CATEGORY_OF_MOVIE TEXT,
DESCRIPTION_OF_MOVIE TEXT,
TYPE_OF_SHOW VARCHAR(100)
);

-- IMPORTING THE DATA FROM CSV FILE INTO MYSQL.
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\NETFLIX.CSV'
INTO TABLE NETFLIX_DATASET
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Show_id, title, director, cast, country, date_added, released_year, rating, duration, category_of_movie, description_of_movie, type_of_show);	
commit;

SHOW CREATE TABLE NETFLIX_DATASET;
DESCRIBE NETFLIX_DATASET;
SELECT * FROM NETFLIX_DATASET;

-- Performing 20+ Analytical SQL queries on the Netflix dataset using MySQL.

-- 1. COUNT THE NUMBER OF MOVIES VS TV SHOWS.
SELECT * FROM NETFLIX_DATASET;
SELECT TYPE_OF_SHOW, COUNT(*) AS TOTAL_COUNT FROM NETFLIX_DATASET GROUP BY TYPE_OF_SHOW;

-- 2. FIND THE TOP 5 COUNTRIES WITH THE MOST CONTENT ON NETFLIX.
SELECT * FROM NETFLIX_DATASET;
SELECT COUNTRY,COUNT(*) AS TOTAL_COUNT FROM NETFLIX_DATASET GROUP BY COUNTRY ORDER BY TOTAL_COUNT DESC LIMIT 5;

-- 3. LIST ALL THE MOVIES THAT ARE DOCUMENTARIES.
SELECT * FROM NETFLIX_DATASET;
SELECT TITLE,CATEGORY_OF_MOVIE,TYPE_OF_SHOW FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE "%MOVIE%" AND CATEGORY_OF_MOVIE LIKE "%DOCUMENTARIES%";

-- 4. IDENTIFY THE LONGEST MOVIE
SELECT * FROM NETFLIX_DATASET;
SELECT TITLE,CONCAT(CAST(REPLACE(DURATION,'min','') AS UNSIGNED), ' min') AS LONGEST_MOVIE,TYPE_OF_SHOW FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE "%MOVIE%" ORDER BY CAST(REPLACE(DURATION,'min','') AS UNSIGNED) DESC LIMIT 1;
-- 												OR (ANOTHER WAY TO DO THIS)
SELECT TITLE,CONCAT(REPLACE(DURATION,'min',''), 'min') AS DURATION,TYPE_OF_SHOW FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE "%MOVIE%" AND DURATION > 300;

-- 5. COUNT THE NUMBER OF CONTENT ITEMS IN EACH GENRE
SELECT * FROM NETFLIX_DATASET;
SELECT CATEGORY_OF_MOVIE,COUNT(*) AS TOTAL_COUNT FROM NETFLIX_DATASET GROUP BY CATEGORY_OF_MOVIE ORDER BY TOTAL_COUNT DESC;

-- 6. LIST ALL MOVIES RELEASED IN A SPECIFIC YEAR (e.g., 2018)
SELECT * FROM NETFLIX_DATASET;
SELECT TITLE,TYPE_OF_SHOW,RELEASED_YEAR FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE "%MOVIE%" AND RELEASED_YEAR = 2018;

-- 7. FIND THE CONTENT ADDED IN THE LAST 5 YEARS
SELECT * FROM NETFLIX_DATASET;
SELECT * FROM NETFLIX_DATASET WHERE RELEASED_YEAR BETWEEN 2015 AND 2020 ORDER BY RELEASED_YEAR;

-- 8. FIND ALL MOVIES/TV SHOWS BY DIRECTOR 'RAJIV CHILAKA'
SELECT * FROM NETFLIX_DATASET;
SELECT * FROM NETFLIX_DATASET WHERE DIRECTOR LIKE "%RAJIV CHILAKA%";

-- 9. LIST ALL THE TV SHOWS WITH MORE THAN 5 SEASONS
SELECT * FROM NETFLIX_DATASET;
SELECT TITLE,DURATION FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE "%TV SHOW%" AND CAST(REPLACE(REPLACE(DURATION,'SEASONS',''), 'SEASON','') AS UNSIGNED) > 5;

-- 10. FIND ALL CONTENT WITHOUT A DIRECTOR
SELECT * FROM NETFLIX_DATASET;
SELECT * FROM NETFLIX_DATASET WHERE DIRECTOR IS NULL OR DIRECTOR = '';

-- 11. FIND HOW MANY MOVIES ACTOR 'SALMAN KHAN' RELEASED IN THE LAST 10 YEARS
SELECT * FROM NETFLIX_DATASET;
SELECT TYPE_OF_SHOW,COUNT(*) AS "TOTAL MOVIES" FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE "%MOVIE%" AND CAST LIKE "%SALMAN KHAN%" AND RELEASED_YEAR BETWEEN 2010 AND 2020 GROUP BY TYPE_OF_SHOW;

-- 12. IDENTIFY MOVIES/TV SHOW FEATURING A SPECIFIC ACTOR (e.g., "Robert De Niro")
SELECT * FROM NETFLIX_DATASET;
SELECT TITLE,CAST,TYPE_OF_SHOW FROM NETFLIX_DATASET WHERE CAST LIKE "%ROBERT DE NIRO%";

-- 12.5 HOW MANY MOVIES/TV SHOW FEATURING A SPECIFIC ACTOR (e.g., "Robert De Niro")
SELECT * FROM NETFLIX_DATASET;
SELECT COUNT(*) FROM (SELECT TITLE,CAST,TYPE_OF_SHOW FROM NETFLIX_DATASET WHERE CAST LIKE "%ROBERT DE NIRO%") AS SUB;

-- 13. GROUP THE RECORDS BY YEAR AND COUNT THE NUMBER OF MOVIES/TV SHOWS ADDED EACH YEAR  
SELECT * FROM NETFLIX_DATASET;
SELECT RELEASED_YEAR,COUNT(*) AS TOTAL_COUNT FROM NETFLIX_DATASET GROUP BY RELEASED_YEAR;

-- 13.5 GROUP THE RECORDS BY YEAR AND TYPE_OF_SHOW COUNT THE NUMBER OF MOVIES/TV SHOWS ADDED EACH YEAR	 	-- ADD IN PROJECT OR NOT
SELECT RELEASED_YEAR,TYPE_OF_SHOW,COUNT(*) AS TOTAL_COUNT FROM NETFLIX_DATASET GROUP BY RELEASED_YEAR,TYPE_OF_SHOW ORDER BY RELEASED_YEAR DESC, TYPE_OF_SHOW;

-- 14. HOW MANY INDIAN MOVIES ARE THERE IN NETFLIX?
SELECT * FROM NETFLIX_DATASET;
SELECT COUNTRY,COUNT(*) AS TOTAL_COUNT FROM NETFLIX_DATASET WHERE COUNTRY = "INDIA" AND TYPE_OF_SHOW LIKE "%MOVIE%" GROUP BY COUNTRY;

-- 15. IDENTIFY THE TOP 3 MOST COMMON GENRES IN THE DATASET.
SELECT * FROM NETFLIX_DATASET;
SELECT CATEGORY_OF_MOVIE, COUNT(*) AS TOP_3_GENRE FROM NETFLIX_DATASET GROUP BY CATEGORY_OF_MOVIE ORDER BY TOP_3_GENRE DESC LIMIT 3;

-- 16. COMPARE THE NUMBER OF MOVIES AND TV SHOWS ADDED BEFORE AND AFTER 2015.
SELECT * FROM NETFLIX_DATASET;

SELECT TYPE_OF_SHOW,COUNT(CASE WHEN RELEASED_YEAR < 2015 THEN 1 END) AS 'BEFORE 2015',
COUNT(CASE WHEN RELEASED_YEAR > 2015 THEN 1 END) AS 'AFTER 2015' FROM NETFLIX_DATASET 
GROUP BY TYPE_OF_SHOW;

-- 17. What are the top 10 most recently released shows.
SELECT * FROM NETFLIX_DATASET;
SELECT TITLE,TYPE_OF_SHOW,RELEASED_YEAR FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE '%TV_SHOW%' ORDER BY RELEASED_YEAR DESC LIMIT 10;

-- 18. FIND THE AVERAGE DURATION OF MOVIES (IN MINUTES).
SELECT * FROM NETFLIX_DATASET;
SELECT CAST(REPLACE(AVG(DURATION),'min','') AS UNSIGNED) AS AVG_MIN FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE "%MOVIE%";

-- 19. LIST ALL THE TV SHOWS WITH MORE THAN 5 SEASONS
SELECT * FROM NETFLIX_DATASET;
SELECT TITLE,DURATION,TYPE_OF_SHOW FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE '%TV SHOW%' AND CAST(REPLACE(REPLACE(DURATION,'SEASONS',''), 'SEASON','') AS UNSIGNED)  > 5;

-- 20. Find the Most Common Rating for Movies and TV Shows
SELECT * FROM NETFLIX_DATASET;
SELECT RATING,COUNT(*) AS MOST_RATING FROM NETFLIX_DATASET GROUP BY RATING ORDER BY MOST_RATING DESC LIMIT 1;

-- 21. List all shows released in the year 2018.
SELECT * FROM NETFLIX_DATASET;
SELECT TITLE,TYPE_OF_SHOW,RELEASED_YEAR FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE "%TV SHOW%" AND RELEASED_YEAR = 2018;

-- 22. How many TV Shows are there.
SELECT * FROM NETFLIX_DATASET;
SELECT COUNT(*) AS "TOTAL NO. OF TV SHOWS" FROM NETFLIX_DATASET WHERE TYPE_OF_SHOW LIKE "%TV SHOW%";

-- 23. FND THE COUNT OF TOTAL NO. OF TV SHOWS THAT HAVE MORE THAN 5 SEASONS.
SELECT * FROM NETFLIX_DATASET;
SELECT COUNT(*) AS TOTAL_COUNT FROM (SELECT TITLE, REPLACE(REPLACE(DURATION,'Seasons','') , 'Season','') AS DURATION FROM NETFLIX_DATASET WHERE DURATION LIKE "%SEASON%" AND DURATION > 5 ORDER BY DURATION) AS SUB;


